version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.3-node
    working_directory: ~/My-Food-Diary/src
    steps:
      - checkout:
          path: ~/My-Food-Diary
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - ruby/install-deps

  rubocop:
    docker:
      - image: cimg/ruby:2.7.3
    working_directory: ~/My-Food-Diary/src
    steps:
      - checkout:
          path: ~/My-Food-Diary
      - run:
          name: Bundle Install
          command: bundle check || bundle install    
      - ruby/install-deps
      - run:
          name: rubocop
          command: bundle exec rubocop --require rubocop-airbnb

  rspec:
    docker:
      - image: cimg/ruby:2.7.3-node
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/My-Food-Diary/src
    steps:
      - checkout:
          path: ~/My-Food-Diary
      - run:
          name: Chrome Driver Install
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install -y unzip
            wget -N http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo chown root:root ~/chromedriver
            sudo chmod 755 ~/chromedriver
            sudo mv ~/chromedriver /usr/bin/chromedriver
            sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -'
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update && sudo apt-get install -y google-chrome-stable
          background: true    
      - run:
          name: Bundle Install
          command: bundle check || bundle install    
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn Install
          command: bundle exec yarn install
      - run: bundle exec bin/webpack
      - run:
          name: rspec
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:2.7.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_rubocop_rspec_and_deploy:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - rubocop
      - deploy:
          requires:
            - rspec
